FROM python:3.12-slim

WORKDIR /app

COPY serverless/serverless_requirements.txt .
RUN pip install --no-cache-dir -r serverless_requirements.txt

COPY serverless ./serverless
COPY pipelines ./pipelines
COPY artifact ./artifact

EXPOSE 8080

CMD ["uvicorn", "serverless.gateway:app", "--host", "0.0.0.0", "--port", "8080"]
